name: Nested workspace dependency installation

on:
  workflow_dispatch:
  push:
    paths:
      - develop

env:
  NODE_VERSION: 16

jobs:
  install-dependencies:
    name: (npm@${{ matrix.version }}) Install the dependencies of the root directory and a nested workspace
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        version: [8.4.0, 8.5.0, 8.5.5]

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # https://github.com/actions/checkout/releases/tag/v2.3.4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954 # https://github.com/actions/setup-node/releases/tag/v2.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install the main dependencies
        run: npm install
      - name: Display the `./node_modules` structure
        run: ls -la ./node_modules
      - name: Install the dependencies of a nested workspace
        run: |
          cd test1
          npm install
      - name: Display the `./node_modules` structure
        run: ls -la ./node_modules
      - name: Display the `./test1/node_modules` structure
        run: ls -la ./test1/node_modules
